#Dev/Dev environment group service.yml File
user-provided:
  - name: dctrn-appdynamics-service
    credentials:
      host-name: wellsfargo-nonprod.saas.appdynamics.com
      port: 443
      account-name: <+secrets.getValue("hashicorpvault://appdctrn_hehv_p/DCTRN/non-prod/appdynamics#accountname")>
      account-access-key: <+secrets.getValue("hashicorpvault://appdctrn_hehv_p/DCTRN/non-prod/appdynamics#accountaccesskey")>
      ssl-enabled: true
      # application-name and tier-name are derived at runtime as <+service.name>-<+env.name>
  - name: jacoco-service
    credentials:
      address: 10.62.23.18
      port: 42389
pipeline-params:
  jacoco-threshold: 80
  pipeline-budget-minutes: 15
  apm-validation-timeout-minutes: 5
